export default [
  'Car', 'Bike', 'Person', 'Plane', 'Train', 'Boat', 'Fighter Jet', 'Rocket', 'Bullet', 'Sound', 'Light',
  'Usain Bolt', 'Cheetah', 'Sonic', 'The Flash', 'Speedy Gonzales', 'Road Runner', 'Speed Racer', 'Speedster',
  'Bullet Train', 'Concorde', 'SR-71 Blackbird', 'F-22 Raptor', 'F-35 Lightning II', 'Peregrine Falcon',
  'Formula 1 Car', 'Bugatti Veyron', 'Koenigsegg Agera RS', 'Hennessey Venom GT', 'Bloodhound SSC', 'Voyager 1',
  'New Horizons', 'Apollo 11', 'Space Shuttle', 'ISS', 'Starship', 'Enterprise', 'Millennium Falcon', 'TIE Fighter',
  'X-Wing', 'Death Star', 'Star Destroyer', 'Borg Cube', 'Warp Drive', 'Hyperdrive', 'Earth\'s Orbit', 'Expansion of The Universe',
  'Goku', 'Superman', 'Thor', 'Hulk', 'Quicksilver', 'Zoom', 'Reverse Flash', 'Savitar', 'Godspeed', 'Black Flash',
  'Sonic the Hedgehog', 'Shadow the Hedgehog', 'Silver the Hedgehog', 'Metal Sonic', 'Amy Rose', 'Tails', 'Knuckles',
  'U-2', 'Land Speed Record', 'Mach 1', 'Mach 2', 'Mach 3', 'Mach 4', 'Mach 5', 'Mach 6', 'Mach 7', 'Mach 8', 'Mach 9', 'Mach 10',
  'Saturn V', 'Soyuz', 'Apollo 13', 'Challenger', 'Columbia', 'Endeavour', 'Discovery', 'Moon\'s Orbit', 'Super Nova',
  'Black Adam', 'Shazam', 'Flash Gordon', 'Captain Marvel', 'Quasar', 'Nova', 'Green Lantern', 'Red Tornado', 'Black Canary',
  'Hurricane', 'Tornado', 'Typhoon', 'Cyclone', 'Twister', 'Storm', 'Thunder', 'Lightning', 'Thunderstorm', 'Supercell',
  'School Bus', 'Truck', 'Van', 'SUV', 'Motorcycle', 'Scooter', 'Rickshaw', 'Bicycle', 'Skateboard', 'Roller Skates',
  'Speedboat', 'Yacht', 'Cruise Ship', 'Submarine', 'Jet Ski', 'Hovercraft', 'Ferry', 'Sailboat', 'Canoe', 'Kayak',
  'Helicopter', 'Airplane', 'Hot Air Balloon', 'Glider', 'Parachute', 'Hang Glider', 'Satellite',
  'Supercar', 'Hypercar', 'Muscle Car', 'Sports Car', 'Convertible', 'Coupe', 'Sedan', 'Hatchback', 'Station Wagon',
  'Pickup Truck', 'Minivan', 'Crossover', 'Limousine', 'Taxi', 'Police Car', 'Ambulance', 'Fire Truck', 'Hearse',
  'Tractor', 'Bulldozer', 'Crane', 'Forklift', 'Dump Truck', 'Garbage Truck', 'Cement Mixer', 'Street Sweeper', 'Snowplow',
  'Snowboarder', 'Skier', 'Snowmobile', 'Ice Skater', 'Ice Hockey Player', 'Figure Skater', 'Speed Skater', 'Curler',
  'Fastball', 'Bowling Ball', 'Golf Ball', 'Snail', 'Turtle', 'Rabbit', 'Gazelle', 'Antelope', 'Horse',
  'Zebra', 'Giraffe', 'Elephant', 'Rhino', 'Hippo', 'Lion', 'Tiger', 'Leopard', 'Jaguar', 'Panther',
  'Puma', 'Cougar', 'Bobcat', 'Lynx', 'Ocelot', 'Serval', 'Caracal', 'Clouded Leopard', 'Snow Leopard', 'Tiger Shark',
  'Great White Shark', 'Hammerhead Shark', 'Mako Shark', 'Bull Shark', 'Whale Shark', 'Blue Whale',
  'Humpback Whale', 'Orca', 'Dolphin', 'Porpoise', 'Seal', 'Sea Lion', 'Walrus', 'Penguin', 'Albatross', 'Eagle',
  'Slug', 'Worm', 'Caterpillar', 'Butterfly', 'Moth', 'Bee', 'Wasp', 'Hornet', 'Ant', 'Grasshopper',
  'Mercury', 'Venus', 'Earth', 'Mars', 'Jupiter', 'Saturn', 'Uranus', 'Neptune', 'Pluto', 'Sun', 'Moon',
  'Tachyon', 'Neutrino', 'Photon', 'Electron', 'Proton', 'Neutron', 'Quark', 'Lepton', 'Boson', 'Hadron',
  'Parker Solar Probe', 'Instant Transmission', 'Black Hole', 'Gravitational Waves', 'First Airplane', 'First Car',
  'First Train', 'First Rocket', 'First Bullet Train', 'First Supersonic Flight', 'First Manned Spaceflight',
];